# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='default title', max_length=100),
            preserve_default=False,
        ),
    ]
