# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interested',
            field=models.ManyToManyField(related_name='interested_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
