# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160503_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
