# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.Subject'),
        ),
    ]
